import fs from "fs";
import os from "os";
import path from "path";
import yaml from "js-yaml";
import { normalizeError } from "./fingerprint";
import type { KnowledgeBaseEntry } from "./knowledgeBase";

export const VALID_TOOLS = ["terraform", "kubernetes", "github-actions"] as const;

export interface LastScanState {
  tool: string;
  rawError: string;
  aiDiagnosis?: { cause: string; fix: string };
  scannedAt: string;
}

function getLastScanPath(): string {
  return path.join(os.homedir(), ".fixdb", "last-scan.json");
}

/** Records the most recent unmatched scan so `fixdb contribute` can default from it. */
export function saveLastScan(state: LastScanState): void {
  const dest = getLastScanPath();
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, JSON.stringify(state, null, 2), "utf8");
}

/** Clears the last-scan record, e.g. once a scan finds a real match. */
export function clearLastScan(): void {
  const dest = getLastScanPath();
  if (fs.existsSync(dest)) fs.rmSync(dest);
}

export function loadLastScan(): LastScanState | undefined {
  const src = getLastScanPath();
  if (!fs.existsSync(src)) return undefined;
  try {
    return JSON.parse(fs.readFileSync(src, "utf8")) as LastScanState;
  } catch {
    return undefined;
  }
}

export function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

/**
 * Derives a starting-point `signature` regex from a raw error: normalizes it
 * the same way matchError() does, then escapes regex metacharacters so the
 * result is safe to use as-is. It's intentionally literal/narrow — a draft
 * for a human to generalize, not a final pattern.
 */
export function buildSignature(rawError: string): string {
  const normalized = normalizeError(rawError);
  const snippet = normalized.length > 200 ? normalized.slice(0, 200) : normalized;
  return snippet.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Renders a knowledge base entry as YAML with a header comment explaining
 * it's a draft that needs human review before being opened as a PR.
 */
export function renderDraftYaml(entry: KnowledgeBaseEntry, fromAiFallback: boolean): string {
  const lines = [
    "# Draft generated by `fixdb contribute` — review before opening a PR.",
    "# - Narrow/generalize the signature regex; as generated it matches this",
    "#   specific error's normalized text, which may be too broad or too narrow.",
  ];
  if (fromAiFallback) {
    lines.push(
      "# - cause/fix originated from the AI fallback diagnosis and were confirmed",
      "#   by this contributor; double-check accuracy before merging."
    );
  }
  return `${lines.join("\n")}\n${yaml.dump(entry, { lineWidth: 100 })}`;
}
