import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "fs";
import os from "os";
import path from "path";
import {
  slugify,
  buildSignature,
  renderDraftYaml,
  saveLastScan,
  loadLastScan,
  clearLastScan,
} from "./contribute";
import type { KnowledgeBaseEntry } from "./knowledgeBase";

test("slugify lowercases, hyphenates, and trims", () => {
  assert.equal(slugify("Pod stuck in ImagePullBackOff!"), "pod-stuck-in-imagepullbackoff");
  assert.equal(slugify("  --leading and trailing--  "), "leading-and-trailing");
});

test("buildSignature escapes regex metacharacters", () => {
  const sig = buildSignature("status 429 (429 QuotaExceeded)");
  assert.doesNotThrow(() => new RegExp(sig));
  assert.ok(new RegExp(sig).test("status 429 (429 quotaexceeded)"));
});

test("buildSignature truncates very long input to 200 chars", () => {
  const longError = "x".repeat(500);
  const sig = buildSignature(longError);
  assert.equal(sig.length, 200);
});

test("renderDraftYaml round-trips as valid, matchable YAML", () => {
  const entry: KnowledgeBaseEntry = {
    id: "kubernetes-test",
    tool: "kubernetes",
    signature: "boom",
    title: "Test",
    cause: "cause text",
    fix: "fix text",
    tags: ["kubernetes"],
    confirmed_by: 1,
  };
  const yaml = require("js-yaml");
  const rendered = renderDraftYaml(entry, false);
  assert.match(rendered, /# Draft generated by `fixdb contribute`/);
  assert.doesNotMatch(rendered, /AI fallback diagnosis/);
  const parsed = yaml.load(rendered);
  assert.deepEqual(parsed, entry);
});

test("renderDraftYaml notes AI-fallback provenance when applicable", () => {
  const entry: KnowledgeBaseEntry = {
    id: "x",
    tool: "terraform",
    signature: "boom",
    title: "Test",
    cause: "c",
    fix: "f",
  };
  assert.match(renderDraftYaml(entry, true), /AI fallback diagnosis/);
});

test("saveLastScan / loadLastScan / clearLastScan round-trip through a fake home dir", () => {
  const originalUserProfile = process.env.USERPROFILE;
  const originalHome = process.env.HOME;
  const fakeHome = fs.mkdtempSync(path.join(os.tmpdir(), "fixdb-fakehome-"));
  process.env.USERPROFILE = fakeHome;
  process.env.HOME = fakeHome;
  try {
    assert.equal(loadLastScan(), undefined);

    saveLastScan({ tool: "terraform", rawError: "boom", scannedAt: "2026-07-30T00:00:00.000Z" });
    const loaded = loadLastScan();
    assert.equal(loaded?.tool, "terraform");
    assert.equal(loaded?.rawError, "boom");

    clearLastScan();
    assert.equal(loadLastScan(), undefined);
  } finally {
    process.env.USERPROFILE = originalUserProfile;
    process.env.HOME = originalHome;
    fs.rmSync(fakeHome, { recursive: true, force: true });
  }
});

test("loadLastScan returns undefined instead of throwing on corrupt state", () => {
  const originalUserProfile = process.env.USERPROFILE;
  const originalHome = process.env.HOME;
  const fakeHome = fs.mkdtempSync(path.join(os.tmpdir(), "fixdb-fakehome-"));
  process.env.USERPROFILE = fakeHome;
  process.env.HOME = fakeHome;
  try {
    fs.mkdirSync(path.join(fakeHome, ".fixdb"), { recursive: true });
    fs.writeFileSync(path.join(fakeHome, ".fixdb", "last-scan.json"), "{ not valid json");
    assert.equal(loadLastScan(), undefined);
  } finally {
    process.env.USERPROFILE = originalUserProfile;
    process.env.HOME = originalHome;
    fs.rmSync(fakeHome, { recursive: true, force: true });
  }
});
